import { normalizeLookupValue } from '../../../assets/utils/normalizeLookupValue.js'

const MAX_LISTING_PAGES = 50

/**
 * Build a public URL for an R2 object key.
 * Each path segment is percent-encoded independently.
 *
 * @param {string} baseUrl - Public bucket base URL (no trailing slash)
 * @param {string} key     - Object key (may contain slashes)
 * @returns {string}
 */
export function toObjectUrl(baseUrl, key) {
  const encodedKey = key
    .split('/')
    .map((segment) => encodeURIComponent(segment))
    .join('/')
  return `${baseUrl}/${encodedKey}`
}

/**
 * Build the public bucket-listing URL for a given prefix.
 *
 * @param {string} baseUrl
 * @param {string} [prefix]
 * @returns {string}
 */
export function toBucketListingUrl(baseUrl, prefix = '') {
  const searchParams = new URLSearchParams({ 'list-type': '2' })
  if (prefix) searchParams.set('prefix', prefix)
  return `${baseUrl}/?${searchParams.toString()}`
}

/**
 * Unescape XML entities in bucket listing responses.
 *
 * @param {string} text
 * @returns {string}
 */
export function decodeXmlEntities(text = '') {
  return text
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&amp;/g, '&')
}

/**
 * List all object keys in an R2 bucket, optionally filtered by a prefix.
 * Follows continuation tokens to page through results.
 *
 * @param {string} baseUrl  - Public bucket base URL (no trailing slash)
 * @param {string} [prefix] - Optional key prefix filter (e.g. "FiccionSonora/")
 * @returns {Promise<string[]>}
 */
export async function fetchBucketKeys(baseUrl, prefix = '') {
  const keys = []
  let continuationToken = ''
  let guard = 0
  const prefixParam = prefix ? `&prefix=${encodeURIComponent(prefix)}` : ''

  while (guard < MAX_LISTING_PAGES) {
    guard += 1
    const tokenParam = continuationToken
      ? `&continuation-token=${encodeURIComponent(continuationToken)}`
      : ''
    const response = await fetch(`${baseUrl}/?list-type=2${prefixParam}${tokenParam}`)
    if (!response.ok) {
      throw new Error(
        `R2 devolvió ${response.status} al leer bucket listing: ${baseUrl}/?list-type=2`,
      )
    }
    const xml = await response.text()

    const keyMatches = xml.matchAll(/<Key>([^<]+)<\/Key>/g)
    for (const match of keyMatches) {
      const key = decodeXmlEntities(match[1]).trim()
      if (key) keys.push(key)
    }

    const nextToken =
      xml.match(/<NextContinuationToken>([^<]+)<\/NextContinuationToken>/)?.[1] ?? ''
    if (!nextToken) break
    continuationToken = decodeXmlEntities(nextToken)
  }

  return keys
}

/**
 * Create a fuzzy key resolver that normalises accents and case when looking up
 * bucket keys.
 *
 * @param {string[]} keys - Full list of bucket keys
 * @returns {{ resolveKey: (requestedKey: string) => string | null }}
 */
export function createKeyResolver(keys = []) {
  const keySet = new Set(keys)
  const normalizedKeyMap = new Map()
  const normalizedFolderMap = new Map()

  for (const key of keys) {
    const normalizedKey = normalizeLookupValue(key)
    if (!normalizedKeyMap.has(normalizedKey)) {
      normalizedKeyMap.set(normalizedKey, key)
    }

    const [folderName] = key.split('/')
    if (folderName) {
      const normalizedFolder = normalizeLookupValue(folderName)
      if (!normalizedFolderMap.has(normalizedFolder)) {
        normalizedFolderMap.set(normalizedFolder, folderName)
      }
    }
  }

  function resolveKey(requestedKey) {
    const sanitized = requestedKey.replace(/^\/+/, '')
    if (keySet.has(sanitized)) return sanitized

    const normalized = normalizeLookupValue(sanitized)
    if (normalizedKeyMap.has(normalized)) return normalizedKeyMap.get(normalized)

    const [requestedFolder, ...rest] = sanitized.split('/')
    if (rest.length === 0) return null

    const resolvedFolder = normalizedFolderMap.get(normalizeLookupValue(requestedFolder))
    if (!resolvedFolder) return null

    const sameFileCandidate = `${resolvedFolder}/${rest.join('/')}`
    if (keySet.has(sameFileCandidate)) return sameFileCandidate

    const normalizedCandidate = normalizeLookupValue(sameFileCandidate)
    if (normalizedKeyMap.has(normalizedCandidate)) {
      return normalizedKeyMap.get(normalizedCandidate)
    }

    return null
  }

  return { resolveKey }
}

/**
 * Fetch and parse `_manifest.json` from the bucket root.
 *
 * The manifest describes the complete file tree of the bucket (equivalent to
 * `dir /s /b` in CMD). Generate it with `node scripts/generate-manifest.js`.
 * Section definitions (layout, labels, colours) remain in `_estructura.json`.
 *
 * Canonical format (generated by scripts/generate-manifest.js):
 * ─────────────────────────────────────────────────────────────
 * {
 *   "version": 1,
 *   "generatedAt": "<ISO-8601>",
 *   "files": [
 *     "Seccion1/video/master.m3u8",
 *     "Seccion1/video/00001.ts",
 *     "_estructura.json"
 *   ]
 * }
 *
 * Legacy formats also accepted by extractManifestKeys (read-only back-compat):
 *   keys:    string[]
 *   objects: Array<{ key: string }>
 *   tree:    nested folder object (leaves: true | null | string | number |
 *            { type: 'file' })
 *
 * @param {string} baseUrl - Public bucket base URL (no trailing slash)
 * @returns {Promise<object|null>} Parsed manifest, or null when absent/invalid
 */
export async function fetchManifest(baseUrl) {
  try {
    const response = await fetch(`${baseUrl}/_manifest.json`)
    if (!response.ok) return null
    return await response.json()
  } catch {
    return null
  }
}

/**
 * Flatten keys from a manifest object.
 *
 * The canonical format is `files: string[]` — a flat recursive list of all
 * object keys, equivalent to the output of `dir /s /b` in CMD.
 * Use `node scripts/generate-manifest.js` to generate it.
 *
 * Also accepts legacy formats for back-compat:
 * - `keys: string[]`
 * - `objects: Array<{ key: string }>`
 * - `tree: object` (nested folder object; file leaves can be `true`, `null`,
 *   string, number, or object with `{ type: 'file' }`)
 *
 * @param {object|null|undefined} manifest
 * @returns {string[]}
 */
export function extractManifestKeys(manifest) {
  if (!manifest || typeof manifest !== 'object') return []

  const fromFlatFiles = Array.isArray(manifest.files) ? manifest.files : null
  if (fromFlatFiles) {
    return fromFlatFiles.filter((key) => typeof key === 'string' && key.trim()).map((key) => key.trim())
  }

  const fromFlatKeys = Array.isArray(manifest.keys) ? manifest.keys : null
  if (fromFlatKeys) {
    return fromFlatKeys.filter((key) => typeof key === 'string' && key.trim()).map((key) => key.trim())
  }

  const fromObjects = Array.isArray(manifest.objects) ? manifest.objects : null
  if (fromObjects) {
    return fromObjects
      .map((entry) => (entry && typeof entry.key === 'string' ? entry.key.trim() : ''))
      .filter(Boolean)
  }

  const tree = manifest.tree
  if (!tree || typeof tree !== 'object') return []

  const keys = []

  function walk(node, currentPath = '') {
    if (!node || typeof node !== 'object' || Array.isArray(node)) return

    for (const [name, value] of Object.entries(node)) {
      if (!name || name === '/') continue
      const nextPath = currentPath ? `${currentPath}/${name}` : name

      if (value && typeof value === 'object' && !Array.isArray(value)) {
        const isFileObject = value.type === 'file'
        if (isFileObject) {
          keys.push(nextPath)
        } else {
          walk(value, nextPath)
        }
        continue
      }

      if (
        value === true ||
        value === null ||
        typeof value === 'string' ||
        typeof value === 'number'
      ) {
        keys.push(nextPath)
      }
    }
  }

  walk(tree)
  return keys
}

/**
 * Fetch and parse a JSON object from R2.
 *
 * @param {string} url   - Full public URL
 * @param {string} label - Human-readable label for error messages
 * @returns {Promise<object>}
 */
export async function fetchJson(url, label) {
  const response = await fetch(url)
  if (!response.ok) {
    throw new Error(`R2 devolvió ${response.status} al leer ${label}: ${url}`)
  }

  try {
    return await response.json()
  } catch {
    throw new Error(`No se pudo parsear JSON en ${label}: ${url}`)
  }
}
